"""New Migration

Revision ID: 8a46a4754b5c
Revises: baefef3ff495
Create Date: 2021-07-13 09:57:19.751351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a46a4754b5c'
down_revision = 'baefef3ff495'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Document', sa.Column('description', sa.String(), nullable=True))
    op.drop_column('Document', 'Description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Document', sa.Column('Description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('Document', 'description')
    # ### end Alembic commands ###
