"""New Migration

Revision ID: a27d2898957e
Revises: c8679737d901
Create Date: 2021-07-12 10:01:13.687526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a27d2898957e'
down_revision = 'c8679737d901'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
