"""New Migration

Revision ID: baefef3ff495
Revises: c9ee506eb290
Create Date: 2021-07-13 09:53:40.368018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baefef3ff495'
down_revision = 'c9ee506eb290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
