"""New Migration

Revision ID: dc350c2ede42
Revises: 8a46a4754b5c
Create Date: 2021-07-13 09:58:35.638108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc350c2ede42'
down_revision = '8a46a4754b5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('new',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_new_id'), 'new', ['id'], unique=False)
    op.drop_index('ix_Document_id', table_name='Document')
    op.drop_table('Document')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Document',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Document_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Document_pkey')
    )
    op.create_index('ix_Document_id', 'Document', ['id'], unique=False)
    op.drop_index(op.f('ix_new_id'), table_name='new')
    op.drop_table('new')
    # ### end Alembic commands ###
